### ISSUE TITLE
Values of LDAP attributes are populated incorrectly

### ISSUE THREAD

**Issue by smianna** [cuba-platform/ldap-addon#12]
When a user logs in to the application using LDAP credentials for the first time, a new CUBA user is created in the system. Currently, values of the *sn* LDAP attribute are not populated from LDAP at all, and values of the *cn* LDAP attribute are set in the *Name* field of the User entity. 

Instead of this, values of the *cn* LDAP attribute have to be set in the *First Name* field and values of *sn* have to be specified in the *Second Name* field.

**Comment by antmarr** [comment]
Add LDAP attributes for First Name and Middle Name on "LDAP Config" tab.
So
LDAP Given Name Attribute = First Name CUBA user attribute.
LDAP Sn Attribute = Second Name CUBA user attribute.
LDAP Middle Name Attribute = Middle Name CUBA user attribute.
LDAP Cn Attribute = Name CUBA user attribute.

**Comment by smianna** [comment]
Verified. 

**Note:** It is necessary to rename fields in the *Attribute Settings* section of LDAP Config Screen as follows:
* Cn Attribute → Name Attribute
* Given Name Attribute → First Name Attribute
* Sn Attribute → Second Name Attribute
