### ISSUE TITLE
Issues related to custom rules

### ISSUE THREAD

**Issue by smianna** [cuba-platform/ldap-addon#18]
1. New custom rules always have the '1' value in the order field. Order numbers of freshly created custom rules should be set in accordance with the existing order, e.g. if there are 4 rules in the system, a new custom rule should have the '5' value in the order field.
2. Rename the attributes in `LdapMatchingRule.java` and UI: *name* and *condition* should be used (attribute captions should be capitalized in the UI).
3. The 'Edit' and 'Remove' buttons should be disabled when a custom rule is selected in the table.

**Comment by antmarr** [comment]
Done. Except 2.

**Comment by smianna** [comment]
The first issue is resolved.

**Comment by smianna** [comment]
Issue №3. **Test-case**
1. Open Menu: LDAP Component → LDAP Matching Rules
2. Select any custom rule in the table.

**ER:** The 'Edit' and 'Remove' buttons are disabled.
**AR:** The buttons are active, however, if I select a custom rule, select another row and go back to custom rule, the buttons become disabled. See the attached GIF for better understanding.

**Note:** Also, is issue occurs when deselecting a custom rule and selecting it again.

![selecting a custom rule](https://user-images.githubusercontent.com/38000666/39698466-ef037600-5205-11e8-8a0e-1ae1bf3865d2.gif)

**Comment by smianna** [comment]
@zaharchenko-evgeny please, take a look at the second point introduced in the ticket. We need your opinion.

**Comment by antmarr** [comment]
@smianna 
Issue №3. Test-case was fixed. Please check it.

**Comment by smianna** [comment]
Issue №3. Verified

**Comment by antmarr** [comment]
Done №2. Please check.

**Comment by smianna** [comment]
Verified
