### ISSUE TITLE
Fix 'disabled' attribute

### ISSUE THREAD

**Issue by smianna** [cuba-platform/ldap-addon#21]
The component mixes up the 'true' and 'false' values of the 'disabled' attribute.

**Comment by antmarr** [comment]
Actually no mixes. My fault that provide bad description of this property.
LDAP stores accountExpires attribute that is 1 whed account disabled and 0 when account enabled.
But CUBA user have isActive property that is 1 whed account enabled and 0 when account disabled.
This lead to misunderstanding. So if you want to disabled user in LDAP you have to set **1** to "accountExpires" attribute.
