### ISSUE TITLE
Ability to restrict login for group with LDAP integration

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/ldap-addon#28]
Ability to restrict login for group with LDAP integration.

https://confluence.atlassian.com/display/CROWD/Restricting+LDAP+Scope+for+User+and+Group+Search

**Comment by antmarr** [comment]
This functionality already present in component.  User base field in LDAP config screen allow to configure arbitrary filter which applies when we search users in LDAP. Now this field was renamed to User Object Filter. 
Example of User Object Filter:
(|(memberOf=cn=Admin,ou=groups,dc=springframework,dc=org)
(memberOf=cn=Developer,ou=groups,dc=springframework,dc=org))
so, only users from Admin and Developer groups could login to aplication
