### ISSUE TITLE
'rule_type' column is duplicated in 'LDAP_MATCHING_RULE' table

### ISSUE THREAD

**Issue by smianna** [cuba-platform/ldap-addon#34]
The following database types were tested for compatibility with the LDAP addon:
* HSQLDB
* PostgreSQL
* Microsoft SQL Server
* Microsoft SQL Server 2005
* Microsoft SQL Server 2012+
* Oracle Database
* MySQL

As a result, the component works properly only when using the PostgreSQL database type. In all other cases, the update scripts fail and the following exception is shown:
```
java.sql.SQLException: Column names in each table must be unique. Column name 'RULE_TYPE' in table 'LDAP_MATCHING_RULE' is specified more than once.
```
The easiest way to reproduce the issue:

**Preconditions:**
* The component should be imported and installed in CUBA Studio.

**Steps to reproduce:**
1. Open the *Samples* tab in Studio and download the *sample-sales* project.
2. Once the project is opened, edit project properties:
* Change the platform version to 6.8.8;
* Select **HSQLDB** in the *Database type* field;
* Click *Apply*;
* Add the component to the *App components* section;
* Open the *Advanced* tab and tick the *Use local maven repository* checkbox;
* Click *OK* to save the changes.
3. Invoke *Run → Create database*.
4. Open the *Data Model* section and click *Generate DB scripts*.
5. Click *Update database*.

**Comment by antmarr** [comment]
This is a bug in studio. For now we generate DB scripts and include them in project for common databases and manually remove duplicate column from them.
