### ISSUE TITLE
Is there a way to check if a user belongs to a certain ou?

### ISSUE THREAD

**Issue by aleksey-stukalov** [cuba-platform/ldap-addon#40]

**Comment by antmarr** [comment]
@aleksey-stukalov I need more details. If you mean UI block with login, ou fields and check button then answer is no.
But you can restrict what users can login to component using User Object Filter property on LDAP Config screen.

**Comment by aleksey-stukalov** [comment]
Normally admins split users by the tree-shaped ou's and treat these ou's as user groups. So, to determine CUBA security rules it is required to know if a user belongs to a specifc ou. See the picture below.

![image](https://user-images.githubusercontent.com/13101773/40610643-4b1f6a64-6284-11e8-8f2b-63d46fc79a9f.png)

So, in matching rules it is required to see what ou a user belongs to.

**Comment by antmarr** [comment]
@aleksey-stukalov You can configure OU attribute name in LDAP Config screen(default is ou). Ou's attribute value will be available in ldapUser property of LdapMatchingRuleContext. Also you can use it in Simple matching rules.

**Comment by aleksey-stukalov** [comment]
@antmarr, this will not work. Following my previous example: user tu belongs to ou users, test-user belongs to both ou's administrators and users. In your approahc, how can I check it in matching rules?

**Comment by aleksey-stukalov** [comment]
Once again - this is a very common requirement, so MUST be included in the component. Not differentiating users by ou's looks odd as this is most used case.

**Comment by antmarr** [comment]
After discussion we decided to add new property to LdapUser class. This property will contain user's LDAP DN.

**Comment by antmarr** [comment]
Task https://github.com/cuba-platform/ldap-addon/issues/43
