### ISSUE TITLE
[LDAP Matching Rules] Caption of Remove button disappears if default rule is selected

### ISSUE THREAD

**Issue by smianna** [cuba-platform/ldap-addon#47]
**Steps to reproduce:**
1. Open Menu: LDAP Component → LDAP Matching Rules.
2. Select the default rule in the table.

**Expected Result:** The 'Remove' button is disabled, however, its caption is shown.
**Actual Result:** The caption of the 'Remove' button disappears after selecting the default rule.
![image](https://user-images.githubusercontent.com/38000666/41536906-fbc7ed7a-7317-11e8-9ca0-6717502cdbea.png)

**Comment by antmarr** [comment]
Done. Please check.

**Comment by smianna** [comment]
Verified.
