### ISSUE TITLE
Wrong access group is assigned if several matching rules are applied

### ISSUE THREAD

**Issue by smianna** [cuba-platform/ldap-addon#48]
**Steps to reproduce:**
1. Open Menu: LDAP Component → LDAP Matching Rules.
2. Create several matching rules that can be applicable to a test user (also, make sure that these rules assign different access groups to a user and none of them have 'Override access group' set to true).
3. Enter the username in the corresponding field.
4. Click *Test Rules*

**Expected Result:** The access group from the matching rule applied the **last** is assigned to the user.
**Actual Result:** The access group from the matching rule applied the **first** is assigned to the user.

**Comment by antmarr** [comment]
Component's behaviour is correct, because matching rules have not 'Override access group'  flag set to true. In this case the first MR set access group to user and other rules don't oveeride this access group.
