### ISSUE TITLE
Restrict substitution of inactive users

### ISSUE THREAD

**Issue by smianna** [cuba-platform/ldap-addon#49]
**Preconditions:**
* 2 users are created (both in LDAP and CUBA).
* User 1 has User 2 as a substituted user.

**Steps to reproduce:**
1. Make User 2 inactive in LDAP.
2. Log in as User 1.
3. Using the lookup field in the right corner of the main menu, switch to User 2.

**Expected Result:** Switching to User 2 is impossible because he is inactive.
When substituting a user, the system should check whether this user is active. If not, then the following system message should be shown: "Sorry, this user cannot be substituted. Please contact your system administrator."
**Actual Result:** It is possible to substitute an inactive user.

**Comment by alx-mag** [comment]
I think there is required some changes of in **CUBA**. There should be provided an ability to register services that will check if user have an ability to login. These services should be called in `com.haulmont.cuba.security.auth.AuthenticationService#substituteUser` method to make their checks. So the services can disable substitution to some users. Thus we can implement a service that will dissable substitution to users that are disabled in LDAP and fix the problem.

**Comment by zhenyazb** [comment]
System message should be shown.
