### ISSUE TITLE
[LDAP Log] Add space between a field name and value

### ISSUE THREAD

**Issue by smianna** [cuba-platform/ldap-addon#52]
1. Open Menu: LDAP Component → LDAP Log.
2. View one of the entries in the table.

Values of *LDAP Attributes*, *User Info Before* and *User Info After* sections do not have spaces (see the picture below).

![image](https://user-images.githubusercontent.com/38000666/41604435-5017d6c8-73f0-11e8-9dfa-cb1a0c23613a.png)

**Comment by antmarr** [comment]
Done. Please check.
