### ISSUE TITLE
Add ability to use domain name in login

### ISSUE THREAD

**Issue by antmarr** [cuba-platform/ldap-addon#62]
Add ability to use domain name in login e.g. HAULMOUNT\admin

**Comment by sergeev-ms** [comment]
Any news about the issue?

**Comment by zaharchenko-evgeny** [comment]
Hi @sergeev-ms,

We are going to include this feature in next LDAP release

**Comment by alx-mag** [comment]
It is possible to use **userPrincipalName** which has _<username@domain>_ pattern (john.doe@example.com).
To enable it go to _LDAP component -> LDAP Config_ and set **Login Attribute** to **userPrincipalName**.

**Comment by sergeev-ms** [comment]
> It is possible to use **userPrincipalName** which has _[username@domain](mailto:username@domain)_ pattern (for example [john.doe@example.com](mailto:john.doe@example.com)).
Thanks
Unfortunately, it`s not enouth for me. Right now users use [domain\username] syntax for login (jespa). I don`t want to breake this behavior.

**Comment by alx-mag** [comment]
The solution is committed on branch [ **ldap-addon-62**](https://github.com/cuba-platform/ldap-addon/tree/ldap-addon-62)

**Comment by sergeev-ms** [comment]
> The solution is committed on branch [ **ldap-addon-62**](https://github.com/cuba-platform/ldap-addon/tree/ldap-addon-62)

Would be it released?

**Comment by alx-mag** [comment]
> > The solution is committed on branch [ **ldap-addon-62**](https://github.com/cuba-platform/ldap-addon/tree/ldap-addon-62)
> 
> Would be it released?

Yes after it's completely rewiewed and tested.

**Comment by sergeev-ms** [comment]
Is't working for me.
Platform 7.1.0 and 1.4-SNAPSHOT addon.
Looks like the problem is in inner class _ActiveDirectoryDomain_ that always use `private static final String CN_USERS = "CN=Users";` for searching users inside the `boolean authenticate(String filter, String password)` method.
