### ISSUE TITLE
User Group and Roles always overridden on user synchronization from LDAP

### ISSUE THREAD

**Issue by petersonbr** [cuba-platform/ldap-addon#65]
Whenever a user logs in, his roles and groups are overridden, even if the flags "override existing access group" and "Override existing roles" are not checked. I'm using Microsoft Active Directory.

I'm using only the default rule:
![image](https://user-images.githubusercontent.com/7387735/52425654-978c2e00-2ae3-11e9-9132-3e111b591fad.png)

Possible causes:
1. Roles: UserSynchronizationServiceBean line 89: all user roles are removed (comment: //user get roles only from LDAP). Later in CubaUserDao line 74 the roles are removed from database .

2. Groups: DbStoredMatchingRuleProcessor line 31: ldapMatchingRuleContext.getGroup() is always null, and so the group is overridden.

**Comment by Velankanniraj** [comment]
Yes.. I am also facing the same issue. Is there any way to avoid the same?
