### ISSUE TITLE
Update demo project

### ISSUE THREAD

**Issue by zhenyazb** [cuba-platform/ldap-addon#77]
1. Update versions to the latest in `build.gradle` for:
 - CUBA
 - add-on
 - hsql

2. Add properties in `web-app.properties` file:
  ldap.expiringSessionNotificationCron = */10 * * * * *
  ldap.addonEnabled = true
  ldap.expiringSessionsEnable = true

**Comment by alx-mag** [comment]
Updated to
Cuba `7.0.9`,
HSQL `2.5.0`,
LDAP add-on `1.3.2`.
