### ISSUE TITLE
Missing db-scripts for mssql

### ISSUE THREAD

**Issue by sergeev-ms** [cuba-platform/ldap-addon#79]
### Environment

- Platform version: 7.1.0
- Addon version: 1.4-SNAPSHOT

**Comment by sergeev-ms** [comment]
Looks like scripts is in there. But I added addon to the existing project and addon tables was not created.
Need to check it on new project.

**Comment by zaharchenko-evgeny** [comment]
Have you previously generated MS SQL scripts by CUBA Studio?
