### ISSUE TITLE
LDAP incorrectly creates duplicated roles for non persistent roles

### ISSUE THREAD

**Issue by zaharchenko-evgeny** [cuba-platform/ldap-addon#93]
### Environment

- Platform version: 7.2.x
- Addon version: 1.5.1

### Description of the bug or enhancement

LDAP addon creates duplicated user roles on each user synchronization if a non-persistent role was applied.
more details in related topic https://www.cuba-platform.ru/discuss/t/oshibka-pri-vhode-s-ispolzvaniem-ldap-addon/4441/10

**Comment by zaharchenko-evgeny** [comment]
Steps to reproduce the issue:
1. user should exist in the application
2. LDAP rule should add a non-persistent role
3. login as a user
4. check that role applied to user and role was not created in DB

**Comment by Desire456** [comment]
Can't reproduce the issue at LDAP 1.5.3 version

**Comment by lovtsovaik** [comment]
For QA: check on 1.6 version

**Comment by owlet1997** [comment]
Can't reproduce the issue at LDAP 1.6-SNAPSHOT version
