### ISSUE TITLE
Custom rule cannot return true

### ISSUE THREAD

**Issue by hbatyrkhan** [cuba-platform/ldap-addon#94]
Custom rules work fine only when an ldap user is entering for the first time, entering an app again after user entity is created in cuba always fails,

1. Enter with an ldap user for the first time
2. Logout
3. Entering again would fail

Custom rules may return false always but I do not think that was the intended action.

**Comment by Desire456** [comment]
I can't reproduce this behavior. May be the problem is in your custom rule implementation.
